### ISSUE TITLE
retrieveUserInfo and retrieveCarInfo do not retrieve data

### ISSUE THREAD

**Issue by naterush** [blockchain-mobility-ecosystem/mobility_dapps#1]
Both of these functions fail to return any information, which Solidity allows. This would result in these functions always returning "empty" tuples. For more info, check out issue here: https://github.com/ethereum/solidity/issues/276.

A simple fix this would be to add the lines

**return (name, license, exists)** on [line 86.](https://github.com/blockchain-mobility-ecosystem/mobility_dapps/blob/master/contracts/CarSharing.sol#L86)

**return (status, owner, IPNSAddr, exists)** on [line 97.](https://github.com/blockchain-mobility-ecosystem/mobility_dapps/blob/master/contracts/CarSharing.sol#L97)

The code could be made more succinct by not setting the variables declared in the function header to the values, and instead just returning the values directly.

**Comment by naterush** [comment]
Oops. I just realized this does not apply as the variables are named in the function header. Sorry for the errant issue. 

P.S. Your demo at Consensus rocked :)

**Comment by Souptacular** [comment]
Thanks @naterush! Appreciate you looking at our code and your compliments :)
